{
 "title": "Lighthouse Report Metrics",
 "time": { "from": "2023-12-14T09:40:50.488Z", "to": "2023-12-14T09:43:14.553Z" },
 "templating": {
  "list": [
   { "name": "metrics", "query": "lighthouse_metrics" },
   {
    "name": "url",
    "label": "Url",
    "query": "show tag values from $metrics with key=\"url\""
   },
   { "name": "score", "label": "Score", "query": "lighthouse_score" },
   { "name": "mode", "label": "Audit mode", "query": "navigation, timespan,snapshot" },
   {
    "name": "metric",
    "label": "Metric",
    "query": "SHOW TAG  VALUES ON lighthouse FROM lighthouse_metrics WITH KEY=\"metric\""
   },
   {
    "name": "category",
    "label": "Category",
    "query": "SHOW TAG  VALUES ON lighthouse FROM lighthouse_score WITH KEY=\"category\""
   }
  ]
 },
 "panels": [
  { "title": "Score", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Recent LH Scores",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"value\" FROM \"lighthouse_score\"\nWHERE \"url\" = '$url' AND \"category\" =~ /$category$/\nGROUP BY \"category\"\nORDER BY time DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "LH scores through time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "query": "SELECT * FROM $score where \"url\"='$url' and \"category\"=~ /$category$/ group by \"category\""
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Recent LH metrics",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT * FROM \"$metrics\" WHERE \"url\"='$url' AND \"gather_mode\"='$mode' AND \"metric\"=~ /$metric$/ GROUP BY \"metric\" ORDER BY \"time\" DESC limit 1"
    }
   ]
  },
  {
   "title": "LH metrics through time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "SELECT * FROM \"$metrics\" where \"url\"='$url' and \"gather_mode\"='$mode' and \"metric\"=~ /$metric$/ group by \"metric\""
    }
   ]
  }
 ]
}